ontology:
  directory_path: ${PROJECT_ROOT}data/ontology/
  ontology_file_name: "chem_ontology.owl"
  base_iri: "http://www.test.org/chem_ontologies/"
  closed_ontology_file_name: "closed_chem_ontology.owl"
  java_exe: "C:/Program Files/Java/jdk-23/bin/java.exe"


LLM:
  model: "gpt-4.1"
  # model: "o1-preview"
  # model: "o1-mini"
  streaming: false
  temperature: 0
  max_tokens: 20000

extractor_examples:
  individual_directory_path:  ${PROJECT_ROOT}data/extractor_examples/concept/
  concept_file_path: "{{individual_directory_path}}concepts.json"

dataset_construction:
  folder_path: ${PROJECT_ROOT}data
  raw_data_folder_path: "{{folder_path}}processed_texts"
  devset_file_path: "{{folder_path}}datasets/devset.json"
  trainset_file_path: "{{folder_path}}datasets/trainset.json"


