apiVersion: v1
kind: Secret
metadata:
    name: des-secrets
    namespace: default
type: Opaque
stringData:
    DASHSCOPE_API_KEY: ENC[AES256_GCM,data:8S+xvX+ltD2MC944PjajWg9FkjO0SRNMg6eqii/cZoWctlA=,iv:PeCD8pDjRpQUFiyyYXzYRWLn1FGnC40usLFRfFXFjAA=,tag:uozFPK/nacdrlkEYNSYm+w==,type:str]
sops:
    age:
        - recipient: age1c7psnl4m7ttpwue84y6fsfr5075awz94h8frqm4d6q35xq9xjyjs3dtvn5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3REVjTnZ1VmVFMGdjZUdH
            MWRadFNXUGcwRTNUaDhLRGxDVjg5NHFRK1NRCk41emdnb2YwOVBmTDl3aGlFclk1
            QTduWGhmbm5lR0MvNGgvVTAyRDV2UDAKLS0tIGR3WjRnY1hscHk0SHFQK3FxTGVx
            QVR1MzQ2TnN1RVdudURNSGp4QUp2Qk0KDOpu368EEJitVP1xvSFd+TkZKjYPjO6L
            vsvIEYNeOUF3YS/Wx7RTY9u3S0ZLBj73qaoH0FDPjfP1NZ8t5JVX2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T08:54:21Z"
    mac: ENC[AES256_GCM,data:EDvah6WSA8wncdHadtBMUfrkLxlx+D3jlY/YX2tyWXWrGGS9F6mRpIX7YMWWpMJ8OKaiJVgAS0SGF8Iv1OqjROElzBRsaCr8fITpzcEh7s88y9HjzMPVRDNr5ICFEwFVX7SjwiOvo2IdUgMRUtycpBUGDPvfOFHwShgTOaH4MEU=,iv:7CUM3q4ywqLWEzowawrCAe8RAT0tfL+IDDcZludaAH0=,tag:vZ8iiI5wINfBjZdeIhOsiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
